### ISSUE TITLE
Application crashes during startup

### ISSUE THREAD

**Issue by Polochon-street** [standardnotes/app#1589]
Hi,

First, thanks for your awesome work, it is a really nice app :)

But now, I am having this problem: after the latest update, the app crashes silently during startup (no crash message, just black screen and disappears).

Apparently, it only happens with my current local notes (which I would very much like to get back, since I don't have an account :sweat_smile: ). I've backed my local data using `adb backup`, and have been able to reproduce using `adb restore` on various android emulator images, ranging from Android 10 to Android 12.

Here is the debug log when trying to run it on an emulator:
```
09/18 12:39:49: Launching 'app-prod-release' on Android 10.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.standardnotes/com.standardnotes.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 12882 on device 'Android_10 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/m.standardnote: Unexpected CPU variant for X86 using defaults: x86
D/SoLoader: init start
D/SoLoader: adding system library source: /vendor/lib
D/SoLoader: adding system library source: /system/lib
D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.standardnotes/lib-main flags = 1]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86 flags = 0]
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.standardnotes/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.standardnotes/lib-main
I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.standardnotes/lib-main
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.standardnotes/lib-main
D/SoLoader: init finish: 4 SO sources prepared
D/SoLoader: init exiting
D/SoLoader: init exiting
D/SoLoader: About to load: libjscexecutor.so
D/SoLoader: libjscexecutor.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libjscexecutor.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libjscexecutor.so
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
W/System.err:     at java.lang.Runtime.load0(Runtime.java:938)
W/System.err:     at java.lang.System.load(System.java:1631)
W/System.err:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
W/System.err:     at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
W/System.err:     at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
W/System.err:     at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:20)
W/System.err:     at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(Unknown Source:0)
W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:352)
W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:319)
W/System.err:     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
W/System.err:     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
W/System.err:     at com.standardnotes.MainApplication.onCreate(MainApplication.java:70)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:219)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found result: 0
D/SoLoader: About to load: libhermes.so
D/SoLoader: libhermes.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libhermes.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libhermes.so
D/SoLoader: Loaded: libhermes.so
D/SoLoader: About to load: libhermes-executor-debug.so
D/SoLoader: libhermes-executor-debug.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libhermes-executor-debug.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libhermes-executor-debug.so
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook6hermes13HermesRuntime11getDebuggerEv" referenced by "/data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86/libhermes-executor-common-debug.so"...
W/System.err:     at java.lang.Runtime.load0(Runtime.java:938)
W/System.err:     at java.lang.System.load(System.java:1631)
W/System.err:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
W/System.err:     at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
W/System.err:     at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:27)
W/System.err:     at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
W/System.err:     at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:370)
W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:319)
W/System.err:     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
W/System.err:     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
W/System.err:     at com.standardnotes.MainApplication.onCreate(MainApplication.java:70)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:219)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: dlopen failed: cannot locate symbol "_ZN8facebook6hermes13HermesRuntime11getDebuggerEv" referenced by "/data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86/libhermes-executor-common-debug.so"... result: 0
D/SoLoader: About to load: libhermes-executor-release.so
D/SoLoader: libhermes-executor-release.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libhermes-executor-release.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libhermes-executor-release.so
D/SoLoader: Loaded: libhermes-executor-release.so
D/SoLoader: init exiting
W/RenderThread: type=1400 audit(0.0:53591): avc: denied { write } for name="property_service" dev="tmpfs" ino=487 scontext=u:r:untrusted_app:s0:c149,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.standardnotes
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
D/SoLoader: About to load: libfbjni.so
D/SoLoader: libfbjni.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libfbjni.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libfbjni.so
D/SoLoader: Loaded: libfbjni.so
V/RNKeychainManager: warming up started at 2252779302274
D/RNKeychainManager: Probe cipher storage: CipherStorageKeystoreAesCbc
D/RNKeychainManager: Selected storage: CipherStorageKeystoreAesCbc
D/SoLoader: About to load: libreactnativejni.so
D/SoLoader: libreactnativejni.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libreactnativejni.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libreactnativejni.so
D/SoLoader: Loaded: libreactnativejni.so
W/unknown:ReactContext: initializeMessageQueueThreads() is called.
E/KeyStore: generateKeyInternal failed on request -68
W/CipherStorageBase: StrongBox security storage is not available.
    android.security.keystore.StrongBoxUnavailableException: Failed to generate key
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:329)
        at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
        at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.generateKey(CipherStorageKeystoreAesCbc.java:228)
        at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:475)
        at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:460)
        at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:413)
        at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:168)
        at com.oblador.keychain.KeychainModule.$r8$lambda$DYujhqpjRgfFQ_gyuwMwyxxqDlk(Unknown Source:0)
        at com.oblador.keychain.KeychainModule$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.security.KeyStoreException: No StrongBox available
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:329) 
        at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 
        at com.oblador.keychain.cipherStorage.CipherStorageKeystoreAesCbc.generateKey(CipherStorageKeystoreAesCbc.java:228) 
        at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:475) 
        at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:460) 
        at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:413) 
        at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:168) 
        at com.oblador.keychain.KeychainModule.$r8$lambda$DYujhqpjRgfFQ_gyuwMwyxxqDlk(Unknown Source:0) 
        at com.oblador.keychain.KeychainModule$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:919) 
V/RNKeychainManager: warming up takes: 37 ms
D/HostConnection: HostConnection::get() New Host Connection established 0x8d677400, tid 12911
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0x99775ec0: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0x99775ec0: ver 3 1 (tinfo 0xec2c05f0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x8d678da0, tid 12911
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3fef39000 size 0x2000
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
D/React:  View manager getCommandsMap:
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.standardnotes.sntextview.TextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
D/EGL_emulation: eglMakeCurrent: 0x99775ec0: ver 3 1 (tinfo 0xec2c05f0)
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaProviderManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.SearchBarManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class org.umhan35.RNSearchBarManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$GroupViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RenderableShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$CircleViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$EllipseViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LineViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RectViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TSpanViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextPathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ImageViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ClipPathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$DefsViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$UseViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$SymbolManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LinearGradientManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RadialGradientManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PatternManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MaskManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ForeignObjectManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MarkerManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.SvgViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativepagerview.PagerViewViewManager
W/unknown:ReactContext: initializeMessageQueueThreads() is called.
D/SoLoader: About to load: libyoga.so
D/SoLoader: libyoga.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libyoga.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libyoga.so
D/SoLoader: Loaded: libyoga.so
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
D/SoLoader: About to load: libreactnativeblob.so
D/SoLoader: libreactnativeblob.so not found on /data/data/com.standardnotes/lib-main
D/SoLoader: libreactnativeblob.so found on /data/app/com.standardnotes-mAZWnMjMQnQGl58uY2EI7g==/lib/x86
D/SoLoader: Not resolving dependencies for libreactnativeblob.so
D/SoLoader: Loaded: libreactnativeblob.so
I/Sodium: Loading C++ library...
I/Sodium: Installing JSI Bindings...
E/unknown:ReactNative: Error: Attempting to get storage key AlwaysOpenWebAppOnLaunch before loading local storage.
    
    This error is located at:
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in RCTView
        in Unknown
        in RCTView
        in Unknown
        in RCTView
        in Unknown
        in Unknown
        in RCTView
        in Unknown
        in A
        in Unknown
        in PanGestureHandler
        in Unknown
        in RCTView
        in Unknown
        in A
        in Unknown
        in RCTView
        in Unknown
        in G
        in Unknown
        in RNSScreen
        in A
        in Unknown
        in U
        in k
        in Unknown
        in RNSScreenContainer
        in ScreenContainer
        in Unknown
        in RCTView
        in Unknown
        in Unknown
        in R
        in RNCSafeAreaProvider
        in Unknown
        in y
        in RNGestureHandlerRootView
        in Unknown
        in w
        in Unknown
        in Unknown
        in Unknown
        in RCTView
        in Unknown
        in RCTView
        in Unknown
        in x
        in _
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in o
        in Unknown
        in RCTView
        in Unknown
        in RCTView
        in Unknown
        in b, js engine: hermes, stack:
    value@715:584700
    value@715:483101
    anonymous@912:2702
    yr@55:41976
    ql@55:90769
    Fa@55:81556
    Ua@55:81458
    La@55:81223
    Ea@55:78199
    dt@55:26084
    _a@55:75288
    Hr@55:48043
    anonymous@718:944
    value@719:3399
    value@719:6478
    value@719:4697
    ?anon_0_@719:1514
    n@281:68
    v@281:279
    tryCallOne@53:15
    anonymous@139:26
    anonymous@82:1671
    k@82:499
    w@82:897
    callReactNativeMicrotasks@82:3053
    value@36:2867
    anonymous@36:959
    value@36:2503
    value@36:918
    value@36:853
W/FPStaticServerModule: Stopped Server
I/Process: Sending signal. PID: 12882 SIG: 9
```

I can also provide the logs for Android 12, but they are very similar and also contain that `E/unknown:ReactNative: Error: Attempting to get storage key AlwaysOpenWebAppOnLaunch before loading local storage.`.

System logcat also says `2022-09-18 12:33:21.134 2015-2128/system_process E/InputDispatcher: channel '3ea3e9f com.standardnotes/com.standardnotes.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!`.

I've tried to downgrade the app to retrieve my data, but installing an earlier version of the app and then restoring it just yield "no data". 

I can of course provide my backup data if needed.

What should I do?

**Comment by Polochon-street** [comment]
Update, for those having the same problems and that would like their data back - I managed to get mine back by using `adb backup`, then extracting the archive, going to `apps/com.standardnotes/db`, then using sqlite, doing a `select * from catalystLocalStorage`, then by copy / pasting, and adding my note to that backup template:
```
{                             
  "version": "004",           
  "items": [                  
    {                         
      "content_type": "SN|ItemsKey",    
      "content": "<key>",
      "created_at_timestamp": 1663490907354000,    
      "created_at": "2022-09-18T08:48:27.354Z",    
      "deleted": false,       
      "enc_item_key": "<key>",
      "updated_at_timestamp": 1663502168069452,    
      "updated_at": "2022-09-18T11:56:08.069Z",    
      "uuid": "326f1559-0b21-4265-a468-f603580f299b"    
    },                        
    {                         
      "content_type": "Note",    
      "content": "<content>",
      "created_at_timestamp": 1663502171440000,    
      "created_at": "2022-09-18T11:56:11.440Z",    
      "deleted": false,       
      "enc_item_key": "<enc item>",
      "items_key_id": "326f1559-0b21-4265-a468-f603580f299b",    
      "updated_at_timestamp": 1663502175120096,    
      "updated_at": "2022-09-18T11:56:15.120Z",    
      "uuid": "d55b2420-9a10-4807-8a77-9fcb0f168ec3"    
    },
...          
  ],                          
  "keyParams": {              
    "identifier": "<you-email@address.com>",    
    "pw_nonce": "<your password nonce, in the db>",    
    "version": "004",         
    "origination": "registration",    
    "created": "1663502164443"    
  }                           
}
```

I was able to recover my notes using the [offline decryption tool](https://github.com/standardnotes/decrypt) :tada:
